spring:
  datasource:
    gov-circle:
      url: jdbc:postgresql://localhost:5432/govcircle
      username: sa
      password: 123
      driver-class-name: org.postgresql.Driver

    cardano-db-sync:
      url: jdbc:postgresql://dbsync-v3.demeter.run:5432/dbsync-preprod
      username: dbsync1dttgevq0ffwg6jruzmq
      password: DmQ+GUVRnpk
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/store/postgresql
    out-of-order: true
    enabled: true
    baseline-on-migrate: true
    execute-in-transaction: false
