spring:
  datasource:
#    gov-circle:
    url: jdbc:postgresql://localhost:5432/govcircle
    username: sa
    password: 123
    driver-class-name: org.postgresql.Driver

#    cardano-db-sync:
#      url: jdbc:postgresql://dbsync-v3.demeter.run:5432/dbsync-preprod
#      username: dbsync1dttgevq0ffwg6jruzmq
#      password: DmQ+GUVRnpk
#      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/store/postgresql
    out-of-order: true
    baseline-on-migrate: true

store:
  cardano:
    host: localhost
    port: 3001
    protocol-magic: 42
#    sync-start-slot: 93398400
#    sync-start-blockhash: 3e6953497e952911d3af467c7b004d5e5d0fa8d79068074f5d65ddb6becb151a
    n2c-host: localhost
    n2c-port: 3333
    devkit-node: true


apiPrefix: /api/v1

logging:
    file:
      name: ./logs/yaci-store.log