package gov.govcircle.constitution.constitution.model.enums;

public enum ActionType {

    MOTION_OF_NO_CONFIDENCE,
    UPDATE_COMMITTEE,
    NEW_CONSTITUTION,
    HF_INITIATION,
    PROTOCOL_PARAMETER_CHANGE,
    PROTOCOL_PARAMETER_CHANGE_ECONOMIC_GROUP,
    PROTOCOL_PARAMETER_CHANGE_TECHNICAL_GROUP,
    PROTOCOL_PARAMETER_CHANGE_GOVERNANCE_GROUP,
    PROTOCOL_PARAMETER_CHANGE_NETWORK_GROUP,
    TREASURY_WITHDRAWAL,
    INFO;
}
